version: '3'

services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1069K09jf
      - POSTGRES_DB=ordersdb